// Code generated by goctl. DO NOT EDIT!
// Source: dtm.proto

package server

import (
	"context"

	"github.com/micro-easy/dtm/cmd/dtmrpc/dtm"
	"github.com/micro-easy/dtm/cmd/dtmrpc/internal/logic"
	"github.com/micro-easy/dtm/cmd/dtmrpc/internal/svc"
)

type DtmServer struct {
	svcCtx *svc.ServiceContext
}

func NewDtmServer(svcCtx *svc.ServiceContext) *DtmServer {
	return &DtmServer{
		svcCtx: svcCtx,
	}
}

func (s *DtmServer) GenGid(ctx context.Context, in *dtm.GenGidReq) (*dtm.GenGidResp, error) {
	l := logic.NewGenGidLogic(ctx, s.svcCtx)
	return l.GenGid(in)
}

func (s *DtmServer) Prepare(ctx context.Context, in *dtm.PrepareReq) (*dtm.PrepareResp, error) {
	l := logic.NewPrepareLogic(ctx, s.svcCtx)
	return l.Prepare(in)
}

func (s *DtmServer) Submit(ctx context.Context, in *dtm.SubmitReq) (*dtm.SubmitResp, error) {
	l := logic.NewSubmitLogic(ctx, s.svcCtx)
	return l.Submit(in)
}

func (s *DtmServer) Check(ctx context.Context, in *dtm.CheckReq) (*dtm.CheckResp, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
