// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dtm.proto

package dtm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenGidReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenGidReq) Reset()         { *m = GenGidReq{} }
func (m *GenGidReq) String() string { return proto.CompactTextString(m) }
func (*GenGidReq) ProtoMessage()    {}
func (*GenGidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{0}
}

func (m *GenGidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenGidReq.Unmarshal(m, b)
}
func (m *GenGidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenGidReq.Marshal(b, m, deterministic)
}
func (m *GenGidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenGidReq.Merge(m, src)
}
func (m *GenGidReq) XXX_Size() int {
	return xxx_messageInfo_GenGidReq.Size(m)
}
func (m *GenGidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenGidReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenGidReq proto.InternalMessageInfo

type GenGidResp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenGidResp) Reset()         { *m = GenGidResp{} }
func (m *GenGidResp) String() string { return proto.CompactTextString(m) }
func (*GenGidResp) ProtoMessage()    {}
func (*GenGidResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{1}
}

func (m *GenGidResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenGidResp.Unmarshal(m, b)
}
func (m *GenGidResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenGidResp.Marshal(b, m, deterministic)
}
func (m *GenGidResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenGidResp.Merge(m, src)
}
func (m *GenGidResp) XXX_Size() int {
	return xxx_messageInfo_GenGidResp.Size(m)
}
func (m *GenGidResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenGidResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenGidResp proto.InternalMessageInfo

func (m *GenGidResp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type Action struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Proto                string   `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	RetryNum             int64    `protobuf:"varint,4,opt,name=retry_num,json=retryNum,proto3" json:"retry_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{2}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Action) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Action) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Action) GetRetryNum() int64 {
	if m != nil {
		return m.RetryNum
	}
	return 0
}

type Step struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action               *Action  `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Compensate           *Action  `protobuf:"bytes,3,opt,name=compensate,proto3" json:"compensate,omitempty"`
	LayerNum             int64    `protobuf:"varint,4,opt,name=layer_num,json=layerNum,proto3" json:"layer_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{3}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Step) GetCompensate() *Action {
	if m != nil {
		return m.Compensate
	}
	return nil
}

func (m *Step) GetLayerNum() int64 {
	if m != nil {
		return m.LayerNum
	}
	return 0
}

type PrepareReq struct {
	Steps                []*Step  `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	FirstExec            int64    `protobuf:"varint,2,opt,name=first_exec,json=firstExec,proto3" json:"first_exec,omitempty"`
	ExpireDuration       int64    `protobuf:"varint,3,opt,name=expire_duration,json=expireDuration,proto3" json:"expire_duration,omitempty"`
	Check                *Action  `protobuf:"bytes,4,opt,name=check,proto3" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareReq) Reset()         { *m = PrepareReq{} }
func (m *PrepareReq) String() string { return proto.CompactTextString(m) }
func (*PrepareReq) ProtoMessage()    {}
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{4}
}

func (m *PrepareReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareReq.Unmarshal(m, b)
}
func (m *PrepareReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareReq.Marshal(b, m, deterministic)
}
func (m *PrepareReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareReq.Merge(m, src)
}
func (m *PrepareReq) XXX_Size() int {
	return xxx_messageInfo_PrepareReq.Size(m)
}
func (m *PrepareReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareReq.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareReq proto.InternalMessageInfo

func (m *PrepareReq) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *PrepareReq) GetFirstExec() int64 {
	if m != nil {
		return m.FirstExec
	}
	return 0
}

func (m *PrepareReq) GetExpireDuration() int64 {
	if m != nil {
		return m.ExpireDuration
	}
	return 0
}

func (m *PrepareReq) GetCheck() *Action {
	if m != nil {
		return m.Check
	}
	return nil
}

type PrepareResp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareResp) Reset()         { *m = PrepareResp{} }
func (m *PrepareResp) String() string { return proto.CompactTextString(m) }
func (*PrepareResp) ProtoMessage()    {}
func (*PrepareResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{5}
}

func (m *PrepareResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareResp.Unmarshal(m, b)
}
func (m *PrepareResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareResp.Marshal(b, m, deterministic)
}
func (m *PrepareResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareResp.Merge(m, src)
}
func (m *PrepareResp) XXX_Size() int {
	return xxx_messageInfo_PrepareResp.Size(m)
}
func (m *PrepareResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareResp.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareResp proto.InternalMessageInfo

func (m *PrepareResp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type SubmitReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Steps                []*Step  `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	FirstExec            int64    `protobuf:"varint,3,opt,name=first_exec,json=firstExec,proto3" json:"first_exec,omitempty"`
	ExpireDuration       int64    `protobuf:"varint,4,opt,name=expire_duration,json=expireDuration,proto3" json:"expire_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitReq) Reset()         { *m = SubmitReq{} }
func (m *SubmitReq) String() string { return proto.CompactTextString(m) }
func (*SubmitReq) ProtoMessage()    {}
func (*SubmitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{6}
}

func (m *SubmitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitReq.Unmarshal(m, b)
}
func (m *SubmitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitReq.Marshal(b, m, deterministic)
}
func (m *SubmitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitReq.Merge(m, src)
}
func (m *SubmitReq) XXX_Size() int {
	return xxx_messageInfo_SubmitReq.Size(m)
}
func (m *SubmitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitReq proto.InternalMessageInfo

func (m *SubmitReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *SubmitReq) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *SubmitReq) GetFirstExec() int64 {
	if m != nil {
		return m.FirstExec
	}
	return 0
}

func (m *SubmitReq) GetExpireDuration() int64 {
	if m != nil {
		return m.ExpireDuration
	}
	return 0
}

type SubmitResp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitResp) Reset()         { *m = SubmitResp{} }
func (m *SubmitResp) String() string { return proto.CompactTextString(m) }
func (*SubmitResp) ProtoMessage()    {}
func (*SubmitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{7}
}

func (m *SubmitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitResp.Unmarshal(m, b)
}
func (m *SubmitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitResp.Marshal(b, m, deterministic)
}
func (m *SubmitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitResp.Merge(m, src)
}
func (m *SubmitResp) XXX_Size() int {
	return xxx_messageInfo_SubmitResp.Size(m)
}
func (m *SubmitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitResp.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitResp proto.InternalMessageInfo

func (m *SubmitResp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type CheckReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReq) Reset()         { *m = CheckReq{} }
func (m *CheckReq) String() string { return proto.CompactTextString(m) }
func (*CheckReq) ProtoMessage()    {}
func (*CheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{8}
}

func (m *CheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReq.Unmarshal(m, b)
}
func (m *CheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReq.Marshal(b, m, deterministic)
}
func (m *CheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReq.Merge(m, src)
}
func (m *CheckReq) XXX_Size() int {
	return xxx_messageInfo_CheckReq.Size(m)
}
func (m *CheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReq proto.InternalMessageInfo

func (m *CheckReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type CheckResp struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResp) Reset()         { *m = CheckResp{} }
func (m *CheckResp) String() string { return proto.CompactTextString(m) }
func (*CheckResp) ProtoMessage()    {}
func (*CheckResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8a7f9533c21f08, []int{9}
}

func (m *CheckResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResp.Unmarshal(m, b)
}
func (m *CheckResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResp.Marshal(b, m, deterministic)
}
func (m *CheckResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResp.Merge(m, src)
}
func (m *CheckResp) XXX_Size() int {
	return xxx_messageInfo_CheckResp.Size(m)
}
func (m *CheckResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResp proto.InternalMessageInfo

func (m *CheckResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GenGidReq)(nil), "dtm.GenGidReq")
	proto.RegisterType((*GenGidResp)(nil), "dtm.GenGidResp")
	proto.RegisterType((*Action)(nil), "dtm.Action")
	proto.RegisterType((*Step)(nil), "dtm.Step")
	proto.RegisterType((*PrepareReq)(nil), "dtm.PrepareReq")
	proto.RegisterType((*PrepareResp)(nil), "dtm.PrepareResp")
	proto.RegisterType((*SubmitReq)(nil), "dtm.SubmitReq")
	proto.RegisterType((*SubmitResp)(nil), "dtm.SubmitResp")
	proto.RegisterType((*CheckReq)(nil), "dtm.CheckReq")
	proto.RegisterType((*CheckResp)(nil), "dtm.CheckResp")
}

func init() { proto.RegisterFile("dtm.proto", fileDescriptor_cf8a7f9533c21f08) }

var fileDescriptor_cf8a7f9533c21f08 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb5, 0x71, 0x62, 0xba, 0x63, 0x91, 0x56, 0x23, 0x1e, 0xac, 0xf0, 0x27, 0xc1, 0x48,
	0x10, 0x04, 0xea, 0x43, 0x38, 0x01, 0x50, 0xd4, 0x37, 0x54, 0xb9, 0xaf, 0x48, 0xd1, 0xc6, 0x1e,
	0xc0, 0x22, 0x76, 0xb6, 0xbb, 0x6b, 0x29, 0xbd, 0x00, 0x12, 0x37, 0xe0, 0x1a, 0x5c, 0x83, 0x53,
	0xa1, 0x9d, 0x75, 0xfe, 0xb4, 0xe4, 0x21, 0x6f, 0x3b, 0xdf, 0x67, 0xcd, 0xfc, 0xbe, 0xdd, 0x31,
	0xc8, 0xd2, 0xd5, 0xe7, 0xda, 0xac, 0xdc, 0x0a, 0xa3, 0xd2, 0xd5, 0x59, 0x02, 0xf2, 0x92, 0x9a,
	0xcb, 0xaa, 0xcc, 0xe9, 0x26, 0x7b, 0x06, 0xb0, 0x29, 0xac, 0xc6, 0x33, 0x88, 0xbe, 0x55, 0x65,
	0x2a, 0x26, 0x62, 0x2a, 0x73, 0x7f, 0xcc, 0x14, 0xc4, 0xef, 0x0b, 0x57, 0xad, 0x1a, 0xef, 0xb5,
	0x66, 0xb9, 0xf1, 0x5a, 0xb3, 0x44, 0x84, 0x7e, 0xa9, 0x9c, 0x4a, 0x7b, 0x2c, 0xf1, 0x19, 0x1f,
	0xc1, 0x80, 0x47, 0xa5, 0x11, 0x8b, 0xa1, 0xc0, 0xc7, 0x20, 0x0d, 0x39, 0x73, 0x3b, 0x6f, 0xda,
	0x3a, 0xed, 0x4f, 0xc4, 0x34, 0xca, 0x4f, 0x58, 0xf8, 0xdc, 0xd6, 0xd9, 0x2f, 0x01, 0xfd, 0x6b,
	0x47, 0xda, 0xf7, 0x6b, 0x54, 0x4d, 0xdd, 0x08, 0x3e, 0xe3, 0x0b, 0x88, 0x15, 0xcf, 0xe7, 0x29,
	0xc9, 0x2c, 0x39, 0xf7, 0x69, 0x02, 0x52, 0xde, 0x59, 0xf8, 0x06, 0xa0, 0x58, 0xd5, 0x9a, 0x1a,
	0xab, 0x1c, 0xf1, 0xe4, 0x7b, 0x1f, 0xee, 0xd9, 0x9e, 0x65, 0xa9, 0x6e, 0xc9, 0xec, 0xb3, 0xb0,
	0xe0, 0x59, 0x7e, 0x0b, 0x80, 0x2b, 0x43, 0x5a, 0x19, 0xca, 0xe9, 0x06, 0xc7, 0x30, 0xb0, 0x8e,
	0xb4, 0x4d, 0xc5, 0x24, 0x9a, 0x26, 0x33, 0xc9, 0x3d, 0x3d, 0x6b, 0x1e, 0x74, 0x7c, 0x0a, 0xf0,
	0xb5, 0x32, 0xd6, 0xcd, 0x69, 0x4d, 0x05, 0x23, 0x46, 0xb9, 0x64, 0xe5, 0xd3, 0x9a, 0x0a, 0x7c,
	0x05, 0xa7, 0xb4, 0xd6, 0x95, 0xa1, 0x79, 0xd9, 0x1a, 0xc5, 0x31, 0x22, 0xfe, 0x66, 0x18, 0xe4,
	0x8b, 0x4e, 0xc5, 0xe7, 0x30, 0x28, 0xbe, 0x53, 0xf1, 0x83, 0x81, 0xee, 0xc1, 0x07, 0x27, 0x1b,
	0x43, 0xb2, 0x25, 0x3b, 0xf8, 0x54, 0x3f, 0x05, 0xc8, 0xeb, 0x76, 0x51, 0x57, 0xce, 0xa3, 0xff,
	0xe7, 0xef, 0xc2, 0xf4, 0x8e, 0x0a, 0x13, 0x1d, 0x11, 0xa6, 0x7f, 0x28, 0x8c, 0xdf, 0xa9, 0x0d,
	0xc7, 0x41, 0xd0, 0x27, 0x70, 0xf2, 0xd1, 0x47, 0x3a, 0x88, 0x99, 0x8d, 0x41, 0x76, 0xae, 0xd5,
	0xdb, 0x15, 0x13, 0xbb, 0x15, 0x9b, 0xfd, 0x11, 0xe0, 0xf7, 0x18, 0x5f, 0x43, 0x1c, 0x56, 0x17,
	0x87, 0x1c, 0x65, 0xbb, 0xd4, 0xa3, 0xd3, 0x3b, 0xb5, 0xd5, 0xf8, 0x16, 0x1e, 0x74, 0x77, 0x87,
	0xc1, 0xdb, 0xbd, 0xf1, 0xe8, 0xec, 0xae, 0x60, 0xb5, 0x6f, 0x1c, 0xf8, 0xbb, 0xc6, 0xdb, 0x4b,
	0xed, 0x1a, 0xef, 0x85, 0x7b, 0x09, 0x03, 0x86, 0xc5, 0x87, 0xec, 0x6c, 0x62, 0x8d, 0x86, 0xfb,
	0xa5, 0xd5, 0x1f, 0xe4, 0xdf, 0x5e, 0x7c, 0xb5, 0xf8, 0x72, 0xe1, 0xea, 0x45, 0xcc, 0xbf, 0xc4,
	0xbb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x21, 0xe5, 0x18, 0x97, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DtmClient is the client API for Dtm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DtmClient interface {
	GenGid(ctx context.Context, in *GenGidReq, opts ...grpc.CallOption) (*GenGidResp, error)
	Prepare(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PrepareResp, error)
	Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error)
	Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error)
}

type dtmClient struct {
	cc *grpc.ClientConn
}

func NewDtmClient(cc *grpc.ClientConn) DtmClient {
	return &dtmClient{cc}
}

func (c *dtmClient) GenGid(ctx context.Context, in *GenGidReq, opts ...grpc.CallOption) (*GenGidResp, error) {
	out := new(GenGidResp)
	err := c.cc.Invoke(ctx, "/dtm.dtm/GenGid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dtmClient) Prepare(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PrepareResp, error) {
	out := new(PrepareResp)
	err := c.cc.Invoke(ctx, "/dtm.dtm/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dtmClient) Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error) {
	out := new(SubmitResp)
	err := c.cc.Invoke(ctx, "/dtm.dtm/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dtmClient) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error) {
	out := new(CheckResp)
	err := c.cc.Invoke(ctx, "/dtm.dtm/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DtmServer is the server API for Dtm service.
type DtmServer interface {
	GenGid(context.Context, *GenGidReq) (*GenGidResp, error)
	Prepare(context.Context, *PrepareReq) (*PrepareResp, error)
	Submit(context.Context, *SubmitReq) (*SubmitResp, error)
	Check(context.Context, *CheckReq) (*CheckResp, error)
}

// UnimplementedDtmServer can be embedded to have forward compatible implementations.
type UnimplementedDtmServer struct {
}

func (*UnimplementedDtmServer) GenGid(ctx context.Context, req *GenGidReq) (*GenGidResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenGid not implemented")
}
func (*UnimplementedDtmServer) Prepare(ctx context.Context, req *PrepareReq) (*PrepareResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedDtmServer) Submit(ctx context.Context, req *SubmitReq) (*SubmitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (*UnimplementedDtmServer) Check(ctx context.Context, req *CheckReq) (*CheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterDtmServer(s *grpc.Server, srv DtmServer) {
	s.RegisterService(&_Dtm_serviceDesc, srv)
}

func _Dtm_GenGid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenGidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtmServer).GenGid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtm.dtm/GenGid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtmServer).GenGid(ctx, req.(*GenGidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dtm_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtmServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtm.dtm/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtmServer).Prepare(ctx, req.(*PrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dtm_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtmServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtm.dtm/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtmServer).Submit(ctx, req.(*SubmitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dtm_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtmServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtm.dtm/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtmServer).Check(ctx, req.(*CheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dtm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dtm.dtm",
	HandlerType: (*DtmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenGid",
			Handler:    _Dtm_GenGid_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Dtm_Prepare_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _Dtm_Submit_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Dtm_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dtm.proto",
}
